#!/bin/sh /etc/rc.common
START=75
STOP=10

start() {
	mkdir -p -m777 /var/run/vpnc
	vpncwatch -c twitter.com -p 80 -i 300 vpnc /etc/vpnc/vpnc.conf >/dev/null 2>&1
}

stop() {
	killall vpncwatch
	PID_F=/var/run/vpnc/pid
	if [ -f $PID_F ]; then
		PID=$(cat $PID_F)
		kill $PID
		while [ -d /proc/$PID ];
		do
			sleep 1
		done
	fi
}

