#!/bin/sh

case "$1" in
	start)
		echo "Starting dnsmasq daemon..."
		/opt/sbin/dnsmasq -n -c 0 -N -C /opt/etc/dnsmasq.conf -u root
		;;
	stop)
		echo "Shutting down dnsmasq daemon..."
		killall dnsmasq
		;;
	restart)
		$0 stop
		sleep 2
		$0 start
		;;
	*)
		echo $"Usage: $0 {start|stop|restart}"
esac

