#!/bin/sh

case "$1" in
	start)
		echo "Starting SyncY daemon..."
		/opt/bin/syncy.py &
		;;
	stop)
		echo "Shutting down SyncY daemon..."
		[ -e /var/run/syncy.pid ] && {
			sypid=$(cat /var/run/syncy.pid)
			kill $sypid
		}
		;;
	restart)
		$0 stop
		sleep 2
		$0 start
		;;
	*)
		echo $"Usage: $0 {start|stop|restart}"
esac

