#!/bin/sh

case "$1" in
	start)
		echo "Starting transmission daemon..."
		/opt/bin/transmission-daemon -B -C -y -p 9091 -a *.*.*.* -g /opt/etc/transmission -w /shares/Media/Downloads/Temp --no-incomplete-dir -t -u admin -v asdf
		sleep 1
		/opt/bin/transmission-remote 127.0.0.1:9091 --auth=admin:asdf -tall --start
		;;
	stop)
		echo "Shutting down transmission daemon..."
		/opt/bin/transmission-remote 127.0.0.1:9091 --auth=admin:asdf -tall --stop
		sleep 2
		killall transmission-daemon
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo $"Usage: $0 {start|stop|restart}"
esac

