#!/bin/sh

case "$1" in
	start)
		echo "Starting Transmission daemon..."
		/opt/bin/transmission-daemon -B -a *.*.*.* -g /opt/etc/transmission -w /shares/Media/Downloads/TEMP --no-incomplete-dir
		;;
	stop)
		echo "Shutting down Transmission daemon..."
		killall transmission-daemon
		;;
	restart)
		$0 stop
		sleep 2
		$0 start
		;;
	*)
		echo $"Usage: $0 {start|stop|restart}"
esac

