#!/bin/sh

#Google and YouTube
route add -net 8.8.0.0/16 dev ppp1
route add -net 74.125.0.0/16 dev ppp1 
route add -net 61.238.0.0/16 dev ppp1
route add -net 173.194.0.0/16 dev ppp1
route add -net 208.117.0.0/16 dev ppp1
#Facebook
route add -net 31.13.0.0/16 dev ppp1
route add -net 173.252.0.0/16 dev ppp1
#Twitter
route add -net 199.59.0.0/16 dev ppp1
#DWNews
route add -net 209.246.0.0/16 dev ppp1
#Dropbox
route add -net 199.47.0.0/16 dev ppp1
#Westca
route add -net 50.22.0.0/16 dev ppp1
#BlogCDN
route add -net 23.15.0.0/16 dev ppp1
#WordPress
route add -net 72.233.0.0/16 dev ppp1
#Wikipedia
route add -net 208.80.0.0/16 dev ppp1

echo CONNECTED: `date` >> /var/log/chroute.log

